### ISSUE TITLE
Failed at the QuickMock@0.0.1 start script 'supervisor ./bin/www'.

### ISSUE THREAD

**Issue by Anonymous-Monk** [zouyifeng/QuickMock#1]
[npm-debug.log](https://github.com/zouyifeng/QuickMock/files/1628311/npm-debug.log)
192:QuickMock zero$ npm start

> QuickMock@0.0.1 start /Users/zero/Desktop/QuickMock
> supervisor ./bin/www

sh: supervisor: command not found

**Comment by zouyifeng** [comment]
hi,I just upgraded it, it may fix this problem
